#ifndef ALARMCOMMAND_H
#define ALARMCOMMAND_H

typedef enum {START_ALARM, STOP_ALARM, START_ENTRY_DELAY, STOP_ENTRY_DELAY, START_EXIT_DELAY, STOP_EXIT_DELAY} AlarmCommand;

#endif /* ALARMCOMMAND_H */
